package adminui

import (
	"embed"
	"io/fs"
	"net/http"
	"strings"
)

// distFS holds the built web console (Vite output). It is regenerated by
// `make web` (pnpm build) and committed so the single binary builds anywhere.
//
//go:embed all:web/dist
var distFS embed.FS

// spaHandler serves the embedded console: a static asset when the path maps to one, else
// index.html so client-side routes (e.g. /models/x/versions/y) resolve (§06.1).
func spaHandler() http.Handler {
	sub, err := fs.Sub(distFS, "web/dist")
	if err != nil {
		panic("adminui: embedded web/dist missing (run `make web`): " + err.Error())
	}
	fileServer := http.FileServer(http.FS(sub))
	index, _ := fs.ReadFile(sub, "index.html")

	return http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		p := strings.TrimPrefix(req.URL.Path, "/")
		if p != "" {
			if f, err := sub.Open(p); err == nil {
				_ = f.Close()
				fileServer.ServeHTTP(w, req)
				return
			}
		}
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write(index)
	})
}
