#!/usr/bin/env python3
"""Generate the OpenAPI manifest the hand-written ergonomic SDK routes its requests through.

The SDK deliberately keeps generated surface data separate from ergonomic upload/download code,
but the ergonomic layer builds every URL from the generated PATHS table — so a path or operation
that moves in the contract surfaces here at generation time rather than as a 404 at runtime.

Run from the repository root: ``python3 sdk/generate.py``.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "internal/api/modelapi/openapi.json"
OUT = ROOT / "sdk/python/lineage/_openapi.py"

# The operations the ergonomic layer routes through. Generation fails if the contract drops one.
REQUIRED = {
    "createModel", "publishVersion", "transitionVersion", "resolve", "initiateUpload",
    "finalizeUpload", "uploadContent", "fetchContent", "addLineage", "listLineage",
}

spec = json.loads(SPEC.read_text())
paths: dict[str, tuple[str, str]] = {}
for path, item in spec["paths"].items():
    for method, operation in item.items():
        if isinstance(operation, dict) and "operationId" in operation:
            paths[operation["operationId"]] = (method.upper(), path)

if missing := REQUIRED - set(paths):
    raise SystemExit(f"OpenAPI contract is missing SDK operations: {', '.join(sorted(missing))}")

lines = [
    "# Generated by sdk/generate.py from internal/api/modelapi/openapi.json; do not edit.",
    f"API_VERSION = {spec['info']['version']!r}",
    "",
    "# operationId -> (HTTP method, path template). The client resolves every URL through this.",
    "PATHS = {",
]
lines += [f"    {op!r}: {pair!r}," for op, pair in sorted(paths.items())]
lines += ["}", "", "OPERATIONS = tuple(PATHS)", ""]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(ROOT)}: {len(paths)} operations, API {spec['info']['version']}")
